### ISSUE TITLE
Make delimiter character (e.g. underscore, hyphens) to be configurable

### ISSUE THREAD

**Issue by haikalpribadi** [graknlabs/bazel-deps#1]
The reason we made a fork of this repo is to make the delimiter character to be hyphens (`-`) rather than an underscore (`_`). However, it is best to not fork off upstream. Thus, let's improve this fork further to make the delimiter character to be configurable, and submit a PR to upstream.

**Comment by vmax** [comment]
We instead decided to not do that and use underscores (`_`) in our target names.
