### ISSUE TITLE
Allow setting license type per dependency

### ISSUE THREAD

**Issue by haikalpribadi** [graknlabs/bazel-deps#2]

**Comment by vmax** [comment]
@haikalpribadi could you elaborate on what's needed here?

**Comment by vmax** [comment]
@haikalpribadi also, given that `bazel` is doing pretty big rework on licensing mechanisms in `BUILD` files, current implementation might be rendered obsolete as soon as we finish it.

**Comment by haikalpribadi** [comment]
alright let's hold off on this for a while then, @vmax

**Comment by vmax** [comment]
@haikalpribadi let's reopen once we have a proper definition to avoid cluttering issues
